### PR TITLE
Renamed setting, added KeeperFX.CFG

### PR DESCRIPTION
**Pull request by Loobinex**
also put the setting in a more logical place, and replaced few tabs with spaces.

### CODE REVIEW

**Comment by Loobinex** [comment]
I looked at it, and it seems ok to me. Do you want to test it further or are you happy with it?

**Comment by AdamPlenty** [comment]
> 
> 
> I looked at it, and it seems ok to me. Do you want to test it further or are you happy with it?

Might want to change the pitch range for the repeating sound to apply to any sound, but other than that it seems to be okay.

**Comment by Loobinex** [comment]
ok, we can still look into the log message not appearing,.. after we're satisfied with that I'll merge.

As for the pitch range, at first the pitch range for all sounds was the same, but I changed it because of your feedback. If they are all the same, either the drops did not reach the correct highs/lows, or the other sounds got too extreme.

**Comment by AdamPlenty** [comment]
The drops have a higher range in pitch than the other sounds (and yes, they're supposed to).

**Pull request merged**
